### ISSUE TITLE
Thoughts about Backlog and Next

### ISSUE THREAD

**Issue by janvv** [janvv/outlook-taskboard#12]
I was thinking of these two columns the other day....

The way I work is that I take a few items from the Backlog and put them in the Next column as the work I am going to do the next few days. From there they go In Progress etc...

In fact you should keep the Backlog out of the view because it distracts you from the work you should focus on. When you open the Kanban board the Next column is what you should see.  (Compare it to a Scrum sprint)
Ideally, you should only go back to the Backlog when your Next column is empty. Of course we do not live in an ideal world, so there are always urgent tasks coming along, that should go into the Next lane immediately. That's why it is useful to be able to add tasks to the Next column, skipping the Backlog.

I am curious to read your thoughts about this.

**Comment by Shrekmachine** [comment]
Actually most of the time I create tasks in the next column.

**Comment by janvv** [comment]
I have an Outlook Quick Step to turn emails into tasks. Those go into the Tasks folder by default. And by setting the Start Date properly (thanks @haweidner) they will show up on my Kanban's backlog in time.

**Comment by BillyMcSkintos** [comment]
I like the idea of a distraction free view and I could get behind this if a) it was a configuration option and b) I could view the backlog from the board.

**Comment by janvv** [comment]
It can now be configured which task folders are displayed
