### ISSUE TITLE
Category colors don't work when a task has more than one category

### ISSUE THREAD

**Issue by janvv** [janvv/outlook-taskboard#16]

**Comment by BillyMcSkintos** [comment]
Hi @Janvv, if I take this commit, is OneNote integration still removed?

**Comment by BillyMcSkintos** [comment]
Personally, I use OneNote and the integration every day. I would be delighted if you could restore it.

**Comment by janvv** [comment]
Ok, np

**Comment by janvv** [comment]
done

**Comment by BillyMcSkintos** [comment]
Perfect, thank you!

**Comment by Shrekmachine** [comment]
all my labels are simply just black on white. I replaced all files ecept config which I added the line 
    'USE_CATEGORY_COLORS': true,

**Comment by janvv** [comment]
Hmm... my screen looks like this: 
![image](https://user-images.githubusercontent.com/4539260/29808260-9b1d02f6-8c97-11e7-8cde-890a5304d271.png)

My config is:
![image](https://user-images.githubusercontent.com/4539260/29808319-db97ae62-8c97-11e7-8c4d-28eea67ea585.png)

**Comment by janvv** [comment]
I already realize what your problem might be: I guess you are not taking the master branch. I'll remove the category-color branch, which is outdated.

**Comment by Shrekmachine** [comment]
Hmm, I just jumped into the project and downloaded from the "Master" Button.
