### ISSUE TITLE
Move Onenote Icon before edit and trash can

### ISSUE THREAD

**Issue by BillyMcSkintos** [janvv/outlook-taskboard#21]
Hi @janvv,

I couldn't figure out a pull request from my kanban.html but would it possible to move the onenote implementation/icons above the edit and trash can icons? That way the icons remain in the same location.

**Comment by BillyMcSkintos** [comment]
Moved OneNote glyph:

`<!doctype html>

<html ng-app="taskboardApp">

<head>
    <title>Outlook Task Board</title>
    <meta http-equiv="X-UA-Compatible" content="IE=11">

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/taskboard.css">

    
    <script src="lib/jquery.min.js"></script>
    <script src="lib/jquery-ui.min.js"></script>
    <script src="lib/angular.js"></script>
    <script src="lib/sortable.min.js"></script>
    <script src="lib/moment.min.js"></script>
    <script src="lib/minify.json.js"></script>
    <script src="lib/deep-diff-0.3.8.min.js"></script>
    <script src="js/app.js"></script>

</head>

<body ng-controller="taskboardController" ng-init="init()">

    <div class="taskboard container-fluid">

        
        <section id="filterbar" class="row">
            <div class="col-md-12">
                <div class="input-group">
                    <div class="input-group-addon"><strong>Outlook Taskboard</strong></div>
                    <div class="input-group-addon">
                        <button id="refreshbutton" class="btn btn-default btn-xs" aria-label="Refresh" type="button" ng-click="initTasks();"><span class="glyphicon glyphicon-refresh" aria-hidden="true"></span></button>
                    </div>
                    <div ng-show="(search != '')" class="input-group-addon">
                        <button class="btn btn-default btn-xs" aria-label="Clear" type="button" ng-click="search = ''"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
                    </div>
                    <input type="text" name="search" ng-model="search" class="form-control" placeholder="Filter" />
                    <div class="input-group-addon">
                        <button class="btn btn-default btn-xs" aria-label="Report" type="button" ng-click="createReport();"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span></button>
                    </div>
                    <div ng-show="(usePrivate && private == true)" class="input-group-addon">
                        <button class="btn btn-default btn-xs" ng-model="private" aria-label="Private" type="button" ng-click="private = !private"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></button>
                    </div>
                    <div ng-show="(usePrivate && private == false)" class="input-group-addon">
                        <button class="btn btn-default btn-xs" ng-model="private" aria-label="Public" type="button" ng-click="private = !private"><span class="glyphicon glyphicon-globe" aria-hidden="true"></span></button>
                    </div>
                    <div class="input-group-addon">
                        <button class="btn btn-default btn-xs" aria-label="Config" type="button" ng-click="editConfig();"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
                    </div>
                    <div class="input-group-addon">
                        <button class="btn btn-default btn-xs" aria-label="Help" ng-click="displayHelp();"><strong>?</strong></button>
                    </div>
                </div>
            </div>
        </section>

        
        <section class="row">

            
            <div ng-if="( config.BACKLOG_FOLDER.ACTIVE )" class="tasklane col-md-3 col-sm-4 col-xs-6" ng-class=" { 'col-lg-100' : numfolders === 1, 'col-lg-50' : numfolders === 2, 'col-lg-33' : numfolders === 3, 'col-lg-25': numfolders === 4, 'col-lg-20': numfolders === 5 }">
                <div class="panel panel-default">
                    <header class="panel-heading-todo">
                        <h5>{{ config.BACKLOG_FOLDER.TITLE }}
                            <span class="pull-right">
                                <button class="btn btn-default btn-xs" aria-label="Add" type="button" ng-click="addTask('backlog');"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
                            <span class="label label-info">{{ backlogTasks.length }}</span>
                            </span>
                        </h5>
                    </header>
                    <ul id="backlogList" ui-sortable="sortableOptions" ng-model="filteredBacklogTasks" class="panel-body tasklist list-unstyled">
                        <li ng-repeat="task in filteredBacklogTasks" class="task panel" ng-class=" { 'task-low' : task.priority === 0, 'task-medium' : task.priority === 1, 'task-high' : task.priority === 2, 'task-private': task.sensitivity === 2 }"
                            ng-dblclick="editTask(task)">
                            <header class="panel-heading">
                                {{ task.subject }}
                                <span ng-show="(task.duedate | date:'yyyy' ) != '4501'" ng-class="isOverdue(task.duedate)" class="pull-right">(Due: {{ task.duedate | date:config.DATE_FORMAT }}) </span>
                            </header>
                            <div class="panel-body"> {{ task.notes }} </div>
                            <footer class="text-right">
                                <div ng-if="( config.BACKLOG_FOLDER.DISPLAY_PROPERTIES.OWNER )"><span class="glyphicon glyphicon-user"></span> {{ task.owner }} </div>
                                <div ng-if="( config.BACKLOG_FOLDER.DISPLAY_PROPERTIES.PERCENT )" class="pull-right"> {{ task.percent }}%</div>
                                <div ng-if="(task.categories != '')" class="pull-left"><span class="glyphicon glyphicon-tag"></span>
                                    <span ng-repeat="cat in task.categories"><strong ng-style="cat.style">{{ cat.label }}</strong>&nbsp;</span>
                                </div>
                                <span class="btn-group btn-group-xs">
									<button ng-if="(task.oneNoteURL != '')" class="btn btn-default btn-xs" aria-label="OneNote" type="button" ng-click="openOneNoteURL(task.oneNoteURL)"><span class="glyphicon glyphicon-book" aria-hidden="true"></span></button>
									<button class="btn btn-default btn-xs" aria-label="Edit" type="button" ng-click="editTask(task)"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
									<button class="btn btn-default btn-xs" aria-label="Delete" type="button" ng-click="deleteTask(task,backlogTasks,filteredBacklogTasks, true)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                                </span>
                            </footer>
                        </li>
                    </ul>
                </div>
            </div>
            


            
            <div ng-if="( config.NEXT_FOLDER.ACTIVE )" class="tasklane col-md-3 col-sm-4 col-xs-6" ng-class=" { 'col-lg-100' : numfolders === 1, 'col-lg-50' : numfolders === 2, 'col-lg-33' : numfolders === 3, 'col-lg-25': numfolders === 4, 'col-lg-20': numfolders === 5 }">
                <div class="panel panel-default">
                    <header class="panel-heading-next">
                        <h5>{{ config.NEXT_FOLDER.TITLE }}
                            <span class="pull-right">
                                <button ng-if="( config.NEXT_FOLDER.LIMIT == 0 || nextTasks.length < config.NEXT_FOLDER.LIMIT )" class="btn btn-default btn-xs" aria-label="Add" type="button" ng-click="addTask('next');"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
                            <span class="label label-info">{{ nextTasks.length }}</span> <span ng-if="( config.NEXT_FOLDER.LIMIT > 0 )"
                                class="label label-primary">{{ config.NEXT_FOLDER.LIMIT }}</span>
                            </span>
                        </h5>
                    </header>
                    <ul id="nextList" ui-sortable="sortableOptions" ng-model="filteredNextTasks" class="panel-body tasklist list-unstyled">
                        <li ng-repeat="task in filteredNextTasks" class="task panel" ng-class=" { 'task-low' : task.priority === 0, 'task-medium' : task.priority === 1, 'task-high' : task.priority === 2, 'task-private': task.sensitivity === 2 }"
                            ng-dblclick="editTask(task)">
                            <header class="panel-heading">
                                {{ task.subject }}
                                <span ng-show="(task.duedate | date:'yyyy' ) != '4501'" ng-class="isOverdue(task.duedate)" class="pull-right">(Due: {{ task.duedate | date:config.DATE_FORMAT }}) </span>
                            </header>
                            <div class="panel-body"> {{ task.notes }} </div>
                            <footer class="text-right">
                                <div ng-if="( config.NEXT_FOLDER.DISPLAY_PROPERTIES.OWNER )"><span class="glyphicon glyphicon-user"></span> {{ task.owner }} </div>
                                <div ng-if="( config.NEXT_FOLDER.DISPLAY_PROPERTIES.PERCENT )" class="pull-right"> {{ task.percent }}%</div>
                                <div ng-if="(task.categories != '')" class="pull-left"><span class="glyphicon glyphicon-tag"></span>
                                    <span ng-repeat="cat in task.categories"><strong ng-style="cat.style">{{ cat.label }}</strong>&nbsp;</span>
                                </div>
                                <span class="btn-group btn-group-xs">
									<button ng-if="(task.oneNoteURL != '')" class="btn btn-default btn-xs" aria-label="OneNote" type="button" ng-click="openOneNoteURL(task.oneNoteURL)"><span class="glyphicon glyphicon-book" aria-hidden="true"></span></button>
                                    <button class="btn btn-default btn-xs" aria-label="Edit" type="button" ng-click="editTask(task)"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
									<button class="btn btn-default btn-xs" aria-label="Delete" type="button" ng-click="deleteTask(task,nextTasks,filteredNextTasks, true)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                                </span>
                            </footer>

                        </li>
                    </ul>
                </div>
            </div>
            

            
            <div ng-if="( config.INPROGRESS_FOLDER.ACTIVE )" class="tasklane col-md-3 col-sm-4 col-xs-6" ng-class=" { 'col-lg-100' : numfolders === 1, 'col-lg-50' : numfolders === 2, 'col-lg-33' : numfolders === 3, 'col-lg-25': numfolders === 4, 'col-lg-20': numfolders === 5 }">
                <div class="panel panel-default">
                    <header class="panel-heading-progress">
                        <h5>{{ config.INPROGRESS_FOLDER.TITLE }}
                            <span class="pull-right">
                                <span class="label label-info">{{ inprogressTasks.length }}</span>                            <span ng-if="( config.INPROGRESS_FOLDER.LIMIT > 0 )" class="label label-primary">{{ config.INPROGRESS_FOLDER.LIMIT }}</span>
                            </span>
                        </h5>
                    </header>
                    <ul id="inprogressList" ui-sortable="sortableOptions" ng-model="filteredInprogressTasks" class="panel-body tasklist list-unstyled">
                        <li ng-repeat="task in filteredInprogressTasks" class="task panel" ng-class=" { 'task-low' : task.priority === 0, 'task-medium' : task.priority === 1, 'task-high' : task.priority === 2, 'task-private': task.sensitivity === 2 }"
                            ng-dblclick="editTask(task)">
                            <header class="panel-heading">
                                {{ task.subject }}
                                <span ng-show="(task.duedate | date:'yyyy' ) != '4501'" ng-class="isOverdue(task.duedate)" class="pull-right">(Due: {{ task.duedate | date:config.DATE_FORMAT }}) </span>
                            </header>
                            <div class="panel-body"> {{ task.notes }} </div>
                            <footer class="text-right">
                                <div ng-if="( config.INPROGRESS_FOLDER.DISPLAY_PROPERTIES.OWNER )"><span class="glyphicon glyphicon-user"></span> {{ task.owner }} </div>
                                <div ng-if="( config.INPROGRESS_FOLDER.DISPLAY_PROPERTIES.PERCENT )" class="pull-right"> {{ task.percent }}%</div>
                                <div ng-if="(task.categories != '')" class="pull-left"><span class="glyphicon glyphicon-tag"></span>
                                    <span ng-repeat="cat in task.categories"><strong ng-style="cat.style">{{ cat.label }}</strong>&nbsp;</span>
                                </div>
                                <span class="btn-group btn-group-xs">
									<button ng-if="(task.oneNoteURL != '')" class="btn btn-default btn-xs" aria-label="OneNote" type="button" ng-click="openOneNoteURL(task.oneNoteURL)"><span class="glyphicon glyphicon-book" aria-hidden="true"></span></button>								
                                    <button class="btn btn-default btn-xs" aria-label="Edit" type="button" ng-click="editTask(task)"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
									<button class="btn btn-default btn-xs" aria-label="Delete" type="button" ng-click="deleteTask(task,inprogressTasks,filteredInprogressTasks, true)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                                </span>
                            </footer>

                        </li>
                    </ul>
                </div>
            </div>
            

            <div class="clearfix visible-sm-block"></div>

            
            <div ng-if="( config.WAITING_FOLDER.ACTIVE )" class="tasklane col-md-3 col-sm-4 col-xs-6" ng-class=" { 'col-lg-100' : numfolders === 1, 'col-lg-50' : numfolders === 2, 'col-lg-33' : numfolders === 3, 'col-lg-25': numfolders === 4, 'col-lg-20': numfolders === 5 }">
                <div class="panel panel-default">
                    <header class="panel-heading-waiting">
                        <h5>{{ config.WAITING_FOLDER.TITLE }}
                            <span class="pull-right">
                                <span class="label label-info">{{ waitingTasks.length }}</span>
                            <span ng-if="( config.WAITING_FOLDER.LIMIT > 0 )" class="label label-primary">{{ config.WAITING_FOLDER.LIMIT }}</span>
                            </span>
                        </h5>
                    </header>
                    <ul id="waitingList" ui-sortable="sortableOptions" ng-model="filteredWaitingTasks" class="panel-body tasklist list-unstyled">
                        <li ng-repeat="task in filteredWaitingTasks" class="task panel" ng-class=" { 'task-low' : task.priority === 0, 'task-medium' : task.priority === 1, 'task-high' : task.priority === 2, 'task-private': task.sensitivity === 2 }"
                            ng-dblclick="editTask(task)">
                            <header class="panel-heading">
                                {{ task.subject }}
                                <span ng-show="(task.duedate | date:'yyyy' ) != '4501'" ng-class="isOverdue(task.duedate)" class="pull-right">(Due: {{ task.duedate | date:config.DATE_FORMAT }}) </span>
                            </header>
                            <div class="panel-body"> {{ task.notes }} </div>

                            <footer class="text-right">
                                <div ng-if="( config.WAITING_FOLDER.DISPLAY_PROPERTIES.OWNER )"><span class="glyphicon glyphicon-user"></span> {{ task.owner }} </div>
                                <div ng-if="( config.WAITING_FOLDER.DISPLAY_PROPERTIES.PERCENT )" class="pull-right"> {{ task.percent }}%</div>
                                <div ng-if="(task.categories != '')" class="pull-left"><span class="glyphicon glyphicon-tag"></span>
                                    <span ng-repeat="cat in task.categories"><strong ng-style="cat.style">{{ cat.label }}</strong>&nbsp;</span>
                                </div>
                                <span class="btn-group btn-group-xs">
	                                <button ng-if="(task.oneNoteURL != '')" class="btn btn-default btn-xs" aria-label="OneNote" type="button" ng-click="openOneNoteURL(task.oneNoteURL)"><span class="glyphicon glyphicon-book" aria-hidden="true"></span></button>								
                                    <button class="btn btn-default btn-xs" aria-label="Edit" type="button" ng-click="editTask(task)"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></button>
									<button class="btn btn-default btn-xs" aria-label="Delete" type="button" ng-click="deleteTask(task,waitingTasks,filteredWaitingTasks, true)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                                </span>
                            </footer>

                        </li>
                    </ul>
                </div>
            </div>
            

            
            <div ng-if="( config.COMPLETED_FOLDER.ACTIVE )" class="tasklane col-md-3 col-sm-4 col-xs-6" ng-class=" { 'col-lg-100' : numfolders === 1, 'col-lg-50' : numfolders === 2, 'col-lg-33' : numfolders === 3, 'col-lg-25': numfolders === 4, 'col-lg-20': numfolders === 5 }">
                <div class="panel panel-default">
                    <header class="panel-heading-completed">
                        <h5>{{ config.COMPLETED_FOLDER.TITLE }}
                            <span class="pull-right">
                                <span class="label label-info">{{ completedTasks.length }}</span>
                            </span>
                        </h5>
                    </header>
                    <ul id="completedList" ui-sortable="sortableOptions" ng-model="completedTasks" class="panel-body tasklist list-unstyled">
                        <li ng-repeat="task in filteredCompletedTasks | filter:search" class="task panel task-completed">
                            <header class="panel-heading">
                                {{ task.subject }}
                                <span class="pull-right">(Completed: {{ task.completeddate | date:config.DATE_FORMAT }}) </span>
                            </header>
                            <div class="panel-body"> {{ task.notes }} </div>
                            <footer class="text-right">
                                <div ng-if="( config.COMPLETED_FOLDER.DISPLAY_PROPERTIES.OWNER )"><span class="glyphicon glyphicon-user"></span> {{ task.owner }} </div>
                                <div ng-if="( config.COMPLETED_FOLDER.DISPLAY_PROPERTIES.PERCENT )" class="pull-right"> {{ task.percent }}%</div>
                                <div ng-if="(task.categories != '')" class="pull-left"><span class="glyphicon glyphicon-tag"></span>
                                    <span ng-repeat="cat in task.categories"><strong ng-style="cat.style">{{ cat.label }}</strong>&nbsp;</span>
                                </div>
                                <span class="btn-group btn-group-xs">
	                                <button ng-if="(task.oneNoteURL != '')" class="btn btn-default btn-xs" aria-label="OneNote" type="button" ng-click="openOneNoteURL(task.oneNoteURL)"><span class="glyphicon glyphicon-book" aria-hidden="true"></span></button>							
                                    <button class="btn btn-default btn-xs" aria-label="Archive" type="button" ng-click="archiveTask(task,completedTasks,filteredCompletedTasks)"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button>
									<button class="btn btn-default btn-xs" aria-label="Delete" type="button" ng-click="deleteTask(task,completedTasks,filteredCompletedTasks, true)"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                                </span>
                            </footer>

                        </li>
                    </ul>
                </div>
            </div>
            

        </section>

    </div>




</body>

</html>`

**Comment by janvv** [comment]
Super! I published the change.
