### ISSUE TITLE
Major Issue: Jan so quiet

### ISSUE THREAD

**Issue by Shrekmachine** [janvv/outlook-taskboard#23]
All good?

**Comment by janvv** [comment]
Hahaha

 

Been on vacation first, enjoyed the nice weather at Corfu (but still had my laptop with me to read about Angular)

Secondly we were away a few days with the entire family to celebrate our 35th wedding anniversary, which is quite an exceptional achievement these days J

But the main reason is that I am not quiet at all actually, but working on the revised version I was writing about the other day. I came up with the project name ‘Janban’, and it has its own repository. You can follow the progress there. 

For now I will only make changes to the current outlook-taskboard project if there is a major issue. If not, then I work on the rebuild, which should be easier maintainable and easier configurable.

**Comment by Shrekmachine** [comment]
just let us know when it is worth to move :) *excited*

**Comment by BillyMcSkintos** [comment]
Excited too! Janban!
