### ISSUE TITLE
Issue witht the Task page

### ISSUE THREAD

**Issue by Shrekmachine** [janvv/outlook-taskboard#24]
Hi, today I opened the Kanban page it not opening. I tried to adjust propertieres but there is no possibility to maintain the URL of the Kanban.html
The whole procedure fails
_For Outlook Home page:
Create another folder (of any type) and name it something like "Taskboard" or "Kanban", etc. (Alternatively you can use the main account folder as a home page as well)
Right-click the folder, and then click Properties. Select the Home Page tab in the Properties dialog box.
In the Address box, browse to the folder you have just extracted the Taskboard files and select the kanban.html file._
Any idea what is going on? An Outlook update maybe?

**Comment by janvv** [comment]
It works for me. I'll do a Windows Update and check again.

**Comment by Shrekmachine** [comment]
My Office version: 1708 (Build 8431.2106 Click to run)

 

Cheers Frédéric

**Comment by janvv** [comment]
I am up to date and still no problems.

![image](https://user-images.githubusercontent.com/4539260/31389075-39bfa5d6-add0-11e7-9293-fc7356db0703.png)

Have you already tried to completely remove the folder?
By the way: I am getting an error message when I selected the html file, but after cancelling it is still saved and working.

**Comment by Shrekmachine** [comment]
Even creating a new folder in Tasks I’m not able to set Properties

 

 

 

Cheers Frédéric

**Comment by janvv** [comment]
What exactly is happening? An error message? Or just nothing?
Have you tried to open the html page in IE outside Outlook?

**Comment by Shrekmachine** [comment]
Issue is that I no longer have the “Home” Tab to assign the file location. Look at properties screenshot from previous mail

 

Cheers Frédéric

**Comment by janvv** [comment]
Same issue after I have installed all the latest updates. 👎 
This is really annoying. I'll have a look in the registry and see what I can do under the bonnet.

**Comment by janvv** [comment]
For now I see only one solution: change the home page of the top folder (Outlook Today)
For some reason they removed the Home Page *ON PURPOSE*
I tried the fix here: https://www.slipstick.com/problems/folder-home-pages-arent-available/
But it does not work any more, apparently...

**Comment by janvv** [comment]
I traced down the registry keys that are read by Outlook. The key mentioned in the SlipStick article is still read, but it doesn't work anymore

**Comment by Shrekmachine** [comment]
Hopefully this will not ruin the whole Janban approach

 

Cheers Frédéric

**Comment by janvv** [comment]
Well, as long as the Outlook top level home page remains customizable....
But I was using folders. One for the current outlook taskboard, and another one where I was building and testing the new version. This is really annoying

**Comment by BillyMcSkintos** [comment]
https://github.com/evrenvarol/outlook-taskboard/issues/38

Installing microsoft security update KB4011178 the functionality of setting a alternative home page for task folders is lost. The tab to configuring a home page is lost. The taskboard is not working any more.

**Comment by janvv** [comment]
I found a solution in a Microsoft Technet forum.
Add this Registry key:

[HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Office\16.0\Outlook\Security]
"EnableRoamingFolderHomepages"=dword:00000001

Just tested it, and it works !!

**Comment by Shrekmachine** [comment]
I can confirm. Works again… 

Cheers Frédéric

**Comment by natificent** [comment]
Many thanks Jan. I was looking for a Kanban option, and just found your fork where you've fixed all the issues, and have the registry fix as well. So excited to have Kanban in Outlook.
