### ISSUE TITLE
TotalWork

### ISSUE THREAD

**Issue by LucTech** [janvv/outlook-taskboard#26]
Hi,

Thank you for this job.

I'm intersted in "Total Work" seeing.
I've done the job. 

Seems ok for me at job (outlook 2010).
Modified files : kanban.html (tasks printing) and apps.js (getOutlookFolder, Kanban Config et report's email).

Here are files. 
You may be intersted in integrating them in aoutlook-tackboard repository.

Luc

[kanbantaskboard-totalwork.zip](https://github.com/janvv/outlook-taskboard/files/1567429/kanbantaskboard-totalwork.zip)

**Comment by janvv** [comment]
Very well done!
I appreciate that you added a config option for it for everyone to switch it on or off.
I merged your changes, and only added the config option in the report as well.
Thx.
