### ISSUE TITLE
Startdate

### ISSUE THREAD

**Issue by Gromith** [janvv/outlook-taskboard#27]
When I set a start date on a task in the backlog, the taskboard stops working. When I turn off the autostart function in the config, the taskboard works with startdates.

**Comment by janvv** [comment]
The would be a bug! Rolling up my sleeves, but after Xmas.

**Comment by janvv** [comment]
Hi Gromith,
I have been playing with the autostart option, but I cannot reproduce your issue :-(
The only thing I can think of is that it interferes with one of your other configuration changes.
Can you upload your config.js? That might give more clarity.

**Comment by Gromith** [comment]
Hi janvv,
I tested it again with a clean Installation and Mailbox. Your right :( It is definitely due to one of my modifications. I suspect with the use of the status "deferred". In order to be able to delegate tasks, all tasks must be in the task folder, otherwise updates to the tasks can no longer be updated. That's why I've defined the same folder for all columns. The tasks that are in the column next are displayed twice because they use the same status as the tasks in the backlog. That was the reason why I tried to use the unused status "deferred". it works. but apparently it causes problems with the autostart feature.

I also tried to implement the "Total Time Estimate" feature of rheer's fork. But I had no success so far. Unfortunately, I have never learned a programming language except powershell. Most of the time I try to understand the code and reassemble or complement it with my own logic. :) Sorry for inconvenience.

**Comment by janvv** [comment]
No problem at all.
I am working on a version that should be easier to configure. Unfortunately time is limited, and I have to do it all in my free hours at home.  Anyway, I am enjoying myself developing it, and you guys need some patience :)
