### ISSUE TITLE
Use Start Date as a filter in the Backlog

### ISSUE THREAD

**Issue by janvv** [janvv/outlook-taskboard#4]
Only display tasks when the start date is today or earlier.
Should be configurable because not everyone wants this.

**Comment by janvv** [comment]
@haweidner The start date filter is not that much of a problem:

```
    'BACKLOG_FOLDER': {
      Name: '', Title: 'BACKLOG', Limit: 0, Sort: "duedate,-priority", Restrict: "",
      'SHOW': {
        'OWNER': false,
        'PERCENT': false,
      },
      'FILTER_ON_START_DATE': true,

```
But what about tasks not having a start date? I am tempted to display those in any case.
So only tasks that have a start date in the future will be filtered out. 
Or shall I make an option for that too?

**Comment by haweidner** [comment]
Really great stuff. Exactly this filter was on my kanban wishlist. many thanks.

**Comment by Shrekmachine** [comment]
Please show it always when it has no start date :)

**Comment by haweidner** [comment]
@Shrekmachine this is how it works right now. Love it.

**Comment by haweidner** [comment]
not worth to do any research on this from my point of view, but the counter still keeps untouched by filtering on start dates:

![2017-08-24 10_42_26-outlook task board - outlook](https://user-images.githubusercontent.com/22988059/29658002-acfe6a96-88b9-11e7-8a90-8ec66ca93e4f.jpg)

Best wishes
