### ISSUE TITLE
Use category colors

### ISSUE THREAD

**Issue by janvv** [janvv/outlook-taskboard#5]
Display categories using their colors as configured in Outlook

**Comment by janvv** [comment]
This can be done in different ways:
- Color the glyph-icon
- Color the category text
- Color the background just like the labels on this page
I think the last one would be the nicest. What do you think?

**Comment by Shrekmachine** [comment]
Make it configurable 3:) 
I would prefer to color the category text not to make the board to colorful. Keep the at-a-glance information simple

**Comment by janvv** [comment]
Color the text will be the only option, basically, because tasks can be related to multiple categories.

**Comment by janvv** [comment]
We need at least a mapping from the Category Colors to color codes we can use in CSS. 
https://msdn.microsoft.com/VBA/Outlook-VBA/articles/olcategorycolor-enumeration-outlook

**Comment by janvv** [comment]
The styling begins to work, but there are still some issues to look into:
- I think we should ignore tasks having more than one category
- we still need to find out the correct color codes for styling
- the colors don't seem to match what I have defined in Outlook as the category colors

![image](https://user-images.githubusercontent.com/4539260/29704534-881edf1e-897a-11e7-995a-9040afcda9d1.png)

Have look in the category-colors branch to see the implementation details

**Comment by Shrekmachine** [comment]
take the color of the 1st category . jm2c

**Comment by janvv** [comment]
Fixed the colors. They now match the Outlook categories.
It is not yet good enough. Some colored labels are really bad readable. The yellow ones, for example.
Maybe the rgb values need still some tweaking.
Or we still need to check how it looks when we use the background color instead of the text color.

**Comment by janvv** [comment]
Using color as background:
![image](https://user-images.githubusercontent.com/4539260/29727477-5169b264-89d4-11e7-8f86-7775448ea622.png)

**Comment by Shrekmachine** [comment]
Almost seems that a white font color is better

**Comment by janvv** [comment]
Found a formula to calculate the contrast:
![image](https://user-images.githubusercontent.com/4539260/29729504-b5cbf89a-89dc-11e7-9e9f-397c744417c6.png)

**Comment by janvv** [comment]
@Shrekmachine pushed this to the master branch, including an option in the config to switch using of colors on and off.

**Comment by Shrekmachine** [comment]
good job :)

**Comment by Shrekmachine** [comment]
PS: LIke here? 
![image](https://user-images.githubusercontent.com/8019511/29734257-6baee30c-89f1-11e7-84ef-218adfe3a358.png)

**Comment by janvv** [comment]
Yes, I should be like that. But....
it needs a complete rewrite of the html for the categories as well as the way the categories are stored in the collection of tasks.
It looks like a simple solution, but the implementation is not that straightforward.

**Comment by janvv** [comment]
done :-)

**Comment by Shrekmachine** [comment]
Now an icon is showing even for Tasks without any assigend category
