### ISSUE TITLE
Add a configuration screen

### ISSUE THREAD

**Issue by janvv** [janvv/outlook-taskboard#7]
It would be nice to have a config screen instead of having to change the config.js file

**Comment by Shrekmachine** [comment]
including some CSS configuration for Font type/size :)

**Comment by janvv** [comment]
Giving them an inch... they will take an ell :-)

**Comment by Shrekmachine** [comment]
Yep :D

**Comment by BillyMcSkintos** [comment]
+1

**Comment by janvv** [comment]
Get a copy of the config branch and see if it works.
It completely ignores the config.js file, but saves and reads the config from a Journal item.
When you run it the first time, it takes a default configuration, but you can edit it using the wrench icon top right.
It simply opens that journal entry in edit mode, end the app reloads itself when the item is saved.
I think this is the first step to a config screen. You can at least edit the configuration at runtime now.

**Comment by janvv** [comment]
The big advantage is that you keep your own config when getting a new version of the app :)

**Comment by BillyMcSkintos** [comment]
I like this, thank you!
request: Ability to disable "Next" column and thus adjust the CSS column widths to 25%

**Comment by janvv** [comment]
Gentlemen, please have a look at the latest config branch.
I have added a config option to define which tasks lanes should be active, so you can easily switch the Next and/or the Waiting column off. The width of the columns will be adjusted accordingly. In theory you can have only one column visible at 100% width.
The config is now changed into a journal item, so that it is no longer needed to edit the config.js file.

If no issues are found with this branch I will move the changes to the master version.

**Comment by Shrekmachine** [comment]
I was searching and searching for the config screen ;) 
Seriously, I couldnt find glitches or bugs so far with the config branch.
What happens with the current approach, if the config is enhanced. Will I have to redefine all my personal changes over and over again?
Additionally it would be great if the Font-Size from the taskboard.css could be make configurable as well :)
Great Work though :) Thanks.

**Comment by janvv** [comment]
The idea is that this is the last update where the users have to apply their own configuration again. 
I am working on a way to add new configuration options while the users configuration is kept intact. I am still a bit puzzling ont it, but I am confident I can do it.
